---
# tasks file for ansible-role-mongodb

- name: Check OS version
  assert:
    that:
      - "ansible_distribution == 'Ubuntu'"
    msg: "This role can only be run against Ubuntu. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."

- name: Ensure all variable files based on distribution all loaded
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"

- name: Ensure all tasks based on the distribution are loaded
  include: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"

- name: Ensure MongoDB service is running and enabled
  service:
    name: mongod
    enabled: yes
    state: started
