---
# tasks file for Ubuntu distribution

- name: Ensure apt key for MongoDB is present
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ mongodb_key }}"

- name: Ensure apt repository for MongoDB is present
  apt_repository:
    repo: "{{ mongodb_repo }}"
    filename: mongodb-org-{{ mongodb_version | splitext | first }}
    update_cache: yes
    state: present

- name: Ensure MongoDB package is pinned
  copy:
    dest: /etc/apt/preferences.d/mongodb-org
    content: |
      Package: mongodb-org
      Pin: version {{ mongodb_version }}
      Pin-Priority: 1002

- name: Ensure MongoDB package is present
  apt:
    name: mongodb-org={{ mongodb_version }}
    update_cache: yes
    cache_valid_time: 3600
    state: present

- name: Ensure MongoDB is configured
  template:
    src: templates/mongod.conf.j2
    dest: /etc/mongod.conf
  notify:
    - reload mongod
