---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
  options:
    config-file: molecule/default/.yamllint.yml

platforms:
  - name: instance
    box: ubuntu/xenial64

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default
  test_sequence:
    - destroy
    - lint
    - create
    - converge
    - verify
    - destroy

verifier:
  name: testinfra
  lint:
    name: flake8
